### ISSUE TITLE
Expected ref refs/remotes/origin/main

### ISSUE THREAD

**Issue by geoHeil** [diffplug/spotless-changelog#18]
As mentioned in https://github.com/diffplug/spotless-changelog/issues/16 my issue is not yet fixed by the update to 2.0.1 I still get a:

```
gradle changelogPush
> Task :changelogCheck FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':changelogCheck'.
> Expected ref refs/remotes/origin/main
```

when executing it.

> NOTICE: I run it in a normal non-bare repository where the remote is named origin and the branch origin/main as required by the default settings.

```
git ls-remote
From git@github.com:geoHeil/my_repository.git
hash1	HEAD
hash2	refs/heads/origin/main
```
And `refs/heads/origin/main` is not equal to `refs/remotes/origin/main`.

When I create a remote-tracking branch to get the `refs/remotes/xxx`:

```
git checkout --track origin/main
Branch 'main' folgt nun lokalem Branch 'origin/main'.
Zu neuem Branch 'main' gewechselt
my-repo git:(main) git ls-remote
From .
c1	HEAD
c1	refs/heads/main
c1	refs/heads/origin/main
c1	refs/remotes/origin/HEAD
c1	refs/remotes/origin/origin/main
```

However, `refs/remotes/origin/origin/main` still is not equal to: `refs/remotes/origin/main` and thus spotless-changelog fails again with the same error.

Here is my stack trace for version 2.0.1 and Gradle version 6.8.3
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':changelogCheck'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$3(ExecuteActionsTaskExecuter.java:186)
        ...
Caused by: java.lang.NullPointerException: Expected ref refs/remotes/origin/main
        at com.diffplug.spotless.changelog.GitActions.checkCanPush(GitActions.java:66)
        at com.diffplug.spotless.changelog.gradle.ChangelogPlugin$CheckTask.check(ChangelogPlugin.java:99)
        ...
```

**Comment by nedtwigg** [comment]
Hmm... I wonder if you are using a custom refspec. If I just do a clean clone of this repo, for example: 

```console
foo@bar:~$ git clone https://github.com/diffplug/spotless-changelog
<clone progress etc>
foo@bar:~$ cat .git/config
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = https://github.com/diffplug/spotless-changelog
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
	remote = origin
	merge = refs/heads/main
```

So for the spotless default config:

```gradle
spotlessChangelog {
  remote 'origin'
  branch 'main'
}
```

It is looking for `refs/heads/main` and `refs/remotes/origin/main`. That's the default, plain-jane setup.

I wonder if your origin fetch isn't `+refs/heads/*:refs/remotes/origin/*` but instead something more exotic. I guess one solution is to make

https://github.com/diffplug/spotless-changelog/blob/43e702a9573d1e4a339a4b8fd02be35089fa8dba/spotless-changelog-lib/src/main/java/com/diffplug/spotless/changelog/GitActions.java#L65

smarter, so that it feeds through the origin fetch refspec. A worse option would be to replace `remote` with `remoteRefOverride` which would be null by default, but allow users to bypass the default `refs/remotes/<remote>/<branch>` convention.

Can you confirm the `fetch` key in your `[remote "origin"]` block?

**Comment by geoHeil** [comment]
I observe:

```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = git@github.com:geoHeil/my_repository.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
	remote = c
	merge = refs/heads/main
```

```
+refs/heads/*:refs/remotes/origin/* # yours
+refs/heads/*:refs/remotes/origin/* # mine
```
these are the same.

**Comment by nedtwigg** [comment]
Bizarre. One thing is that it looks like spotless-changelog is on JGit `5.5.1.201910021850-r`, but the latest version is `5.10.0.202012080955-r`. Could be that you've got some cutting edge native git that old JGit can't read.

Maybe try [this workaround](https://github.com/diffplug/spotless/issues/587#issuecomment-657661794) to force the latest JGit version to see if that fixes it?

Also, what's in your `spotlessChangelog` block?

**Comment by geoHeil** [comment]
My version of git is: `2.30.1`

It is not present - as I completely stick to the defaults.

**Comment by nedtwigg** [comment]
Looks like you are using `origin/main` as your branch, with `origin/origin/main` as the remote tracking branch?

Seems like some confusion leftover from a previous fix attempt. I would just use `main`, tracking against `origin/main`.

**Comment by geoHeil** [comment]
Indeed, this is true / finally works.

`> You can set user/pass with any of these environment variables: [GRGIT_USER, GRGIT_PASS, gh_token]`

this is the next step - as I had set up SSH keys & was using the SSH URL I would have expected it to work - will try with the token.

**Comment by geoHeil** [comment]
Works now, but `GRGIT_USER` must point to the user and `gh_token` to the access token and the URL must be an HTTP (not ssh) URL.
