### ISSUE TITLE
Possible regression with -Prelease?

### ISSUE THREAD

**Issue by cereda** [diffplug/spotless-changelog#28]
Hi friends,

We use `appendDashSnapshotUnless_dashPrelease=true` in our projects. In our CI/CD configuration we set the `-Prelease` flag to `true` or `false` depending on pipeline status. However, we noticed a regression here.

Whatever we pass to `-Prelease` that is not `true`, whether `-Prelease` or `-Prelease=false`, we get an error message. For the first case it tells us that it wants `null` but did get `null` which it didn't expect. For the second case it tells us that it expects `true`, `false` or `null`.

```
12* What went wrong:
spotless-changelog expects -Prelease to be either null or 'true', was 'null'
```

Do you have any ideas how we could use `-Prelease` with `true` or `false` value?

Gradle version is 7.3, a failing job log is [available here](https://gitlab.com/islandoftex/albatross/-/jobs/1813077334).

Thanks for the awesome project!

Cheerio,

Paulo

**Comment by nedtwigg** [comment]
Fixed in `2.3.2`
