### ISSUE TITLE
What are the minimum GIT requirements to make changelogPush work?

### ISSUE THREAD

**Issue by ghilainm** [diffplug/spotless-changelog#32]
I am running on gitlab-ci and it seems that the clone performed by gitlab is not enough to make changelogPush works properly.

I am getting the following error:

```
Execution failed for task ':changelogCheck'.
> Expected ref refs/heads/develop
```

Could you update the documentation to provide a bit more insights on the expected requirements to run the task? Can you maybe try to manually retrieve the missing ref if they exist remotely as fallback?

**Comment by nedtwigg** [comment]
Our error message should be better, but I'll dupe this out to #33.
